### PR TITLE
add scoring filter

### PR DESCRIPTION
**Pull request by gcroci2**
In this PR I add the scoring filter component. Some comments:
- A dictionary containing links data is now also saved in `process_uploaded_data`
- At this stage I've implemented filtering in the scoring only for the metcalf method (the only one implemented in the NPLinker)
- Added tests (and fixed the old ones) and docstrings

### CODE REVIEW

**Comment by CunliangGeng** [comment]
Is it ready for review?

**Comment by gcroci2** [comment]
> Is it ready for review?

It is not finished, but I have questions before keep working on it (see the very first comment) @CunliangGeng

**Comment by CunliangGeng** [comment]
Here are my thoughts on your questions:

> Do we want to already have in place the OR/AND logic for the future methods? (in gm_scoring_apply) We can't really test it since we have only one possible scoring method atm

No, we only add them when applicable/needed. Also, we don't need to implement the options for `rosetta` scoring at the moment. So now we'll only implement the following part: 
image
Please keep the selection of scoring methods possible though it's only one choice now.

> How do we want to limit the scoring filter functionality? For example, we could disable it if there are no selected rows in the Data selection table above

Keeping it always enabled and wrapped would make interaction between data table and scoring filter easier.
When needed, users can unwrap it and set the options; otherwise, the default method and values are used. 
If there is no selected rows, clicking `Show spectra` will show an warning message instead of the candidate links table.
image

**Review by CunliangGeng — APPROVED** [review]
Looks great! Just one thing: better to move the button `Set Scoring` outside of scoring container and rename it as e.g. "Show results"? You could work on it in next PR.

**Comment by gcroci2** [comment]
> Looks great! Just one thing: better to move the button `Set Scoring` outside of scoring container and rename it as e.g. "Show results"? You could work on it in next PR.

Okay I've added this point to the next issue (#33)

**Pull request merged**
